version: "25.0.5"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spar
    ports: 
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
  watcher:
    image: node:latest
    volumes:
      - .:/src/app
      - /src/app/node_modules
    working_dir: /src/app
    command: ["npm", "run"]
