version: "3.5"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spar
    ports: 
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    develop:
      watch:
      - action: sync
        path: ./app
        target: /src/app
        ignore:
          - node_modules/
      - action: rebuild
        path: package.json

