name: Run Tests (Test Branch)

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  run:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60  # Increase the timeout to 60 minutes

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [18.x]

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Set up environment variables
        env:
          GOOGLE_ID: ${{ secrets.GOOGLE_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          NEXTAUTH_URL_INTERNAL: ${{ secrets.NEXTAUTH_URL_INTERNAL}}
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}          
        run: echo "Google ID is $GOOGLE_ID. GOOGLE client Secret $GOOGLE_CLIENT_SECRET. MONGODBURI IS $MONGODB_URI"

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: ./spar-med-samvittighed
        run: npm install

      - name: Run npm run build
        working-directory: ./spar-med-samvittighed
        run: npx next build

      - name: Install Selenium WebDriver and Jest
        run: npm install selenium-webdriver @jest/globals

      - name: Run Selenium WebDriver tests
        run: npm test
        env:
          SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub
        working-directory: ./spar-med-samvittighed

      # Optional: Retry strategy for the Selenium service
      - name: Start Selenium service with retry
        run: |
          for i in {1..5}; do
            docker pull selenium/standalone-chrome:latest && break;
            sleep 30;
          done

