name: run test

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Set up environment variables
        env:
          GOOGLE_ID: ${{ secrets.GOOGLE_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          NEXTAUTH_URL_INTERNAL: ${{ secrets.NEXTAUTH_URL_INTERNAL}}
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
        run: echo "Google ID is $GOOGLE_ID. GOOGLE client Secret $GOOGLE_CLIENT_SECRET. MONGODBURI IS $MONGODB_URI"

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: ./spar-med-samvittighed
        run: npm install

      - name: Run npm run build
        working-directory: ./spar-med-samvittighed
        run: npx next build

      - name: Start Selenium in Docker
        run: |
          docker pull selenium/standalone-chrome
          docker run -d --name selenium -p 4444:4444 selenium/standalone-chrome

      - name: Run tests
        working-directory: ./spar-med-samvittighed
        env:
          SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub
        run: |
          export DISPLAY=:99
          npm test

      - name: Stop Selenium container
        if: always()
        run: docker stop selenium && docker rm selenium
