name: Run Tests

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test
jobs:
  run:
    runs-on: ${{ matrix.os }}
 
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [18.x]
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: ./spar-med-samvittighed
        run: npm install

      - name: Run Jest tests
        working-directory: ./spar-med-samvittighed
        run: npm test
